name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install binaries
      run: |
        cargo install -f --verbose cargo-deb cargo-rpm

    - name: get version number
      id: get_version
      run: |
        # get Cargo.toml path
        METADATA_PATH=$(cargo locate-project --message-format plain)
        # get crate version 
        VERSION=$(cargo metadata --no-deps --format-version=1 | jq -r ".packages | map(select(.manifest_path==\"$METADATA_PATH\")) | map(.version) | @tsv")
        echo "::set-output name=crate_version::$VERSION"
  
    - name: build packages
      run: |
        cargo deb
        cargo rpm build

    - name: Archive deb package
      uses: actions/upload-artifact@v3
      with:
        name: sbom-ghr_${{ steps.get_version.outputs.crate_version }}_amd64.deb
        path: target/debian/sbom-ghr_${{ steps.get_version.outputs.crate_version }}_amd64.deb
        retention-days: 3
    
    - name: Archive rpm package
      uses: actions/upload-artifact@v3
      with:
        name: sbom-ghr-${{ steps.get_version.outputs.crate_version }}-1.x86_64.rpm
        path: target/release/rpmbuild/RPMS/x86_64/sbom-ghr-${{ steps.get_version.outputs.crate_version }}-1.x86_64.rpm
        retention-days: 3

    - name: push crates.io
      run: |
        cargo publish --token ${{ secrets.CRATES_IO_API_TOKEN }}
