name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3.0.2
      id: sccache
      with:
        path: |
          ~/.cache/sccache
        key: ${{ runner.os }}-sccache_${{ hashFiles('Cargo.lock') }}

    - uses: actions/cache@v3.0.2
      id: cache-bin
      with:
        path: |
          ~/.cargo/bin
        key: ${{ runner.os }}-cargo-bin_${{ hashFiles('Cargo.lock') }}

    - uses: actions/cache@v3.0.2
      id: cache-vendor
      with:
        path: |
          ./vendor
        key: ${{ runner.os }}-vendor-${{ hashFiles('Cargo.lock') }}

    - name: install binaries
      if: steps.cache-bin.outputs.cache-hit != 'true'
      run: |
        cargo install --verbose cargo-vendor cargo-make cargo-deb cargo-rpm cargo-deny

    - name: Vendor dependencies(fetch)
      if: steps.cache-vendor.outputs.cache-hit != 'true'
      run: |
        cargo vendor > .cargo/config

    - name: Vendor dependencies(cached)
      if: steps.cache-vendor.outputs.cache-hit == 'true'
      run: |
        cp .cargo/config_vendored .cargo/config

    - name: Lint dependencies
      run: |
        cargo deny check

    - name: Build
      run: |
        cargo build --verbose
    
    - name: Run tests
      run: |
        cargo test --verbose
    
    - name: Package
      run: |
        cargo build --release --verbose
        cargo deb
        cargo rpm build

    - name: show cache status
      run: |
        sccache --show-stats
